version: '3.8'
services:
  web:
    build: .
    #command: pip install django==3.1.14|grep pip
    command: python3 manage.py collectstatic
    command: python3 manage.py migrate
    command: /app/expect
    #command: find /app
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8002:8000
